/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vzCff0Q93s1
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function Login() {
  return (
    <div className="mx-auto w-full max-w-sm space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Login</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Enter your email below to login to your account
        </p>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="username">Username</Label>
          <Input id="username" placeholder="m@example.com" required />
        </div>
        <div className="space-y-2">
          <div className="flex items-center">
            <Label htmlFor="password">Password</Label>
            <Link className="ml-auto inline-block text-sm underline" href="#">
              Forgot your password?
            </Link>
          </div>
          <Input id="password" required type="password" />
        </div>
        <Button className="w-full">Login</Button>
      </div>
      <div className="space-y-2 text-center">
        <p className="text-sm">
          Don't have an account?
          <Link href={"/register"}>
            <Button size="sm" variant="outline">
              Register
            </Button>
          </Link>
        </p>
      </div>
    </div>
  );
}
