/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vzCff0Q93s1
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function Register() {
  return (
    <div className="mx-auto w-full max-w-sm space-y-6">
      <div className="border-t border-gray-200 dark:border-gray-800 pt-4">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Register</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Enter your information to create an account
          </p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="new-username">Username</Label>
            <Input id="new-username" placeholder="m" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="new-password">Password</Label>
            <Input id="new-password" type="password" />
          </div>
          <Button className="w-full">Register</Button>
        </div>
      </div>
      <div className="space-y-2 text-center">
        <p className="text-sm">
          Already have an account?
          <Link href={"/login"}>
            <Button size="sm" variant="outline">
              Login
            </Button>
          </Link>
        </p>
      </div>
    </div>
  );
}
